In [29]:
makeVector <- function(x = numeric()) {
        m <- NULL
        set <- function(y) {
                x <<- y
                m <<- NULL
        }
        get <- function() x
        setmean <- function(mean) m <<- mean
        getmean <- function() m
        list(set = set, get = get,
             setmean = setmean,
             getmean = getmean)
}
t<-makeVector(3)

In [39]:
cachemean <- function(x, ...) {
        m <- x$getmean()
        if(!is.null(m)) {
                message("getting cached data")
                return(m)
        }
        data <- x$get()
        m <- mean(data, ...)
        x$setmean(m)
        m
}
cachemean(t)
t$getmean()

getting cached data



[1] 3

[1] 3

In [61]:
X<-cbind(c(-3,5),c(1,0))
X
solve(X)

[,1] [,2]
[1,] -3   1   
[2,]  5   0

[,1] [,2]
[1,] 0    0.2 
[2,] 1    0.6

In [62]:
makeCacheMatrix <- function(x = matrix()) {
        im <- NULL
        set <- function(y) {
                x <<- y
                im <<- NULL
        }
        get <- function() x
        setinv <- function(inv) im <<- inv
        getinv <- function() im
        list(set = set, get = get,
             setinv = setinv,
             getinv = getinv)
}
XX<-makeCacheMatrix(X)
solve(X)

[,1] [,2]
[1,] 0    0.2 
[2,] 1    0.6

In [67]:
cacheSolve <- function(x, ...) {
        im <- x$getinv()
        if(!is.null(im)) {
                message("getting cached data")
                return(im)
        }
        data <- x$get()
        im <- solve(data, ...)
        x$setinv(im)
        im
}

In [68]:
XX$getinv()
cacheSolve(XX)
XX$getinv()

traceback()

NULL

[,1] [,2]
[1,] 0    0.2 
[2,] 1    0.6

[,1] [,2]
[1,] 0    0.2 
[2,] 1    0.6

No traceback available 


In [21]:
XX$getinv()

ERROR: Error in mean(xx): object 'xx' not found


In [69]:
makeCacheMatrix <- function(x = matrix()) {

makeVector <- function(x = matrix()) {
        inv <- NULL
        set <- function(y) {
                x <<- y
                inv <<- NULL
        }
        get <- function() x
        setinverse <- function(inverse) inv <<- inverse
        getinverse <- function() inv
        list(set = set, get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}
}
cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        inv <- x$getinverse()
        if(!is.null(inv)) {
                message("getting cached data")
                return(inv)
        }
        data <- x$get()
        inv <- inverse(data, ...)
        x$setinverse(inv)
        inv
}

In [70]:
X<-cbind(c(-3,5),c(1,0))
X
XX<-makeCacheMatrix(X)
XX
cacheSolve(XX)


[,1] [,2]
[1,] -3   1   
[2,]  5   0

function(x = matrix()) {
        inv <- NULL
        set <- function(y) {
                x <<- y
                inv <<- NULL
        }
        get <- function() x
        setinverse <- function(inverse) inv <<- inverse
        getinverse <- function() inv
        list(set = set, get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}
<environment: 0x0000000004b367e0>

ERROR: Error in x$getinverse: object of type 'closure' is not subsettable
